#!/bin/sh

down() {
brightness=$(brightnessctl g)
brightness=$((brightness-5))
brightnessctl s $brightness
brightness=$(($(brightnessctl g)*100/255))
dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
brightness=$(brightnessctl g)
brightness=$((brightness+5))
brightnessctl s $brightness
brightness=$(($(brightnessctl g)*100/255))
dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
