windowrule = match:title ^(Picture in picture)$, float on
windowrule = match:title ^(Save.+)$, float on
windowrule = match:title ^(Open.+)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:class ^(blueman-manager)$, float on

windowrule = match:title ^(Save File)$, float on
windowrule = match:title ^(Open File)$, float on

# Clipboard manager
windowrule = match:class ^(clipse)$, float on, size 622 652, center on
